### ISSUE TITLE
Revisar uso de lib dotenv

### ISSUE THREAD

**Issue by tomasdelvechio** [pawunlu/clase-api#4]
En la documentación se habla de la función `getenv()` pero al probar el proyecto fallaba (no cargaba la variable), y la que funcionaba es la función `env()`.

Revisar si hace falta arreglar esto.

**Comment by sriccisoft** [comment]
No pude reproducir el problema, pero `env()` es una función del paquete `cakephp/core` no de `vlucas/phpdotenv`.
